name: frontend_parchis
description: "Proyecto de frontend de parchis"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_animate: ^4.5.0
  audioplayers: ^6.0.0
  confetti: ^0.7.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2 
  uuid: ^4.2.1
  http: ^1.2.0
  url_launcher: ^6.2.5 
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.0

  # Firebase & Google Sign-In
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/splash_logo.png
    - assets/fonts/
    - assets/images/
    - assets/tokens/
    - assets/sounds/
    - assets/dice/classic/

  fonts:
    - family: ParchisFont
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoFinal.png"
  web:
    generate: true
    image_path: "assets/icon/logoFinal.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  # ✅ Ponemos el fondo negro para que no "brille" en blanco al principio
  color: "#000000"
  # ✅ Quitamos la imagen de aquí para que no se vea estirada ni nada
  # La imagen la mostrará tu SplashScreen.dart automáticamente
  web: false 
  android_12:
    color: "#000000"
